version: '3.7'

services:
  app:
    image: node:18-alpine
    container_name: mount-db
    working_dir: /usr/app
    ports:
      - "80:8080"
    volumes:
      - ./:/usr/app
    command: npm run build

  npm:
    image: node:18-alpine
    working_dir: /usr/app
    volumes:
      - ./:/usr/app
    entrypoint: ['npm']