version: "3"

networks:
  nginx:
    external: true

services:
  app:
    image: cyberduck/php-fpm-laravel:8.2
    container_name: php-ceramico-backend
    restart: always
    expose:
      - 9000
    volumes:
      - ./:/var/www/ceramico-ecommerce/backend:delegated
    networks:
      nginx:
        aliases:
          - php-ceramico-backend

  composer:
    image: cyberduck/php-fpm-laravel:8.2
    container_name: composer
    volumes:
      - ./:/var/www/ceramico-ecommerce/backend
    working_dir: /var/www/ceramico-ecommerce/backend
    depends_on:
      - app
    entrypoint: ["composer"]

  npm:
    image: node:18
    container_name: npm
    volumes:
      - ./:/var/www/ceramico-ecommerce/backend
    working_dir: /var/www/ceramico-ecommerce/backend
    entrypoint: ["npm"]

  artisan:
    image: cyberduck/php-fpm-laravel:8.2
    container_name: artisan
    volumes:
      - ./:/var/www/ceramico-ecommerce/backend:delegated
    working_dir: /var/www/ceramico-ecommerce/backend
    entrypoint: ["php", "/var/www/ceramico-ecommerce/backend/artisan"]
