version: '3.7'

networks:
  api-network:
    external: true

services:
  app:
    image: node:18-alpine
    container_name: notifications
    command: npm run dev
    restart: always
    working_dir: /usr/app
    volumes:
      - ./:/usr/app
    expose:
      - 3000
    networks:
      - api-network
  
  npm:
    image: node:18-alpine
    volumes:
      - ./:/usr/app
    working_dir: /usr/app
    entrypoint: ["npm"]
